import { faAngleDown, faCirclePlus, faGear, faMagnifyingGlass,  faList, faUsers, faCircle, faBook } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import Image from "next/image";
import Link from "next/link";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <nav className="flex justify-between h-[vh] py-2 items-center px-8 bg-gray-100 border-b-2 border-gray-300 ">
          <h2 className="text-xl font-semibold w-full">Business<span className="bg-yellow-500 ml-2 px-4 rounded-xl">Doc</span></h2>
          <div className="flex justify-start gap-2 border-[2px] py-2 px-2 bg-white w-full rounded-xl" >
            <div className="w-5">  
                    <FontAwesomeIcon icon={faMagnifyingGlass}  />
            </div>          
            <input type="text" className="border-none text-sm w-full focus:outline-none"/>
          </div>
          <div className="w-full flex justify-end gap-2">
            <Image src="/gh-flag.jpeg" alt="Ghana Flag" width={20} height={5}/>
            <h4 className="text-xs ">atmosderrick@gmail.com</h4>
            <div className="flex justify-start items-center gap-2">
                <div className="w-4">
                    <FontAwesomeIcon icon={faGear} />
                </div>

                <div className="w-3"><FontAwesomeIcon icon={faAngleDown} /></div>
            </div>
            </div>
          

        </nav>

 
        <div className="w-1/2 mx-auto mt-12 flex justify-start  ">
            <div className="flex justify-start gap-2 items-center">
                <div className="w-4"><FontAwesomeIcon icon={faCirclePlus} className="text-orange-600" /></div>
                <h3 className="text-base font-medium">New:</h3>
            </div>
            <div className="w-full text-sm font-serif font-normal ">
                <div className="flex justify-center gap-4">
                        <div className="flex justify-start gap-3 items-center">
                        <div className="text-sm w-2"><FontAwesomeIcon icon={faCircle} className="text-gray-900" /></div>
                        <Link href="" className="text-base font-normal">Invoice</Link>
                        </div>

                    <div className="flex justify-start gap-3 items-center">
                        <div className="text-sm w-2"><FontAwesomeIcon icon={faCircle} className="text-gray-900" /></div>
                        <Link href="" className="text-base font-normal">Reciept</Link>
                    </div>

                    <div className="flex justify-start gap-3 items-center">
                        <div className="text-sm w-2"><FontAwesomeIcon icon={faCircle} className="text-gray-900" /></div>
                        <Link href="" className="text-base font-normal">Sale Reciept</Link>
                    </div>

                    <div className="flex justify-start gap-3 items-center">
                        <div className="text-sm w-2"><FontAwesomeIcon icon={faCircle} className="text-gray-900" /></div>
                        <Link href="" className="text-base font-normal">Estimate</Link>
                    </div>

                    <div className="flex justify-start gap-3 items-center">
                    <div className="text-sm w-2"><FontAwesomeIcon icon={faCircle} className="text-gray-900" /></div>
                    <Link href="" className="text-base font-normal">Purchase Note</Link>
                </div>
                </div>

                

                <div className="flex justify-center gap-4 mt-4">
                        <div className="flex justify-start gap-3 items-center">
                        <div className="text-sm w-2"><FontAwesomeIcon icon={faCircle} className="text-gray-900" /></div>
                        <Link href="" className="text-base font-normal">Credit Note</Link>
                    </div>

                    <div className="flex justify-start gap-3 items-center">
                        <div className="text-sm w-2"><FontAwesomeIcon icon={faCircle} className="text-gray-900" /></div>
                        <Link href="" className="text-base font-normal">Delivery Note</Link>
                    </div>

                    <div className="flex justify-start gap-3 items-center">
                        <div className="text-sm w-2"><FontAwesomeIcon icon={faCircle} className="text-gray-900" /></div>
                        <Link href="" className="text-base font-normal">Contract Document</Link>
                    </div>


                </div>
            </div>

        </div>

        <div className='flex justify-start gap-4 w-3/4 mx-auto mt-8'>
            <div><button className='flex justify-center items-center gap-2 text-sm font-medium px-4 py-2 bg-gray-100 rounded-lg border-[2px] border-gray-300 hover:opacity-50 transition-all duration-200'><div className='w-4'><FontAwesomeIcon icon={faList} className='text-blue-600' /></div><h4>My Invoices</h4></button></div>

            <div><button className='flex justify-center items-center gap-2 text-sm font-medium px-4 py-2 bg-gray-100 rounded-lg border-[2px] border-gray-300 hover:opacity-50 transition-all duration-200'><div className='w-4'><FontAwesomeIcon icon={faUsers} className='text-blue-600' /></div><h4>My Customers</h4></button></div>

            <div><button className='flex justify-center items-center gap-2 text-sm font-medium px-4 py-2 bg-gray-100 rounded-lg border-[2px] border-gray-300 hover:opacity-50 transition-all duration-200'><div className='w-4'><FontAwesomeIcon icon={faBook} className='text-blue-600' /></div><h4>My Reports</h4></button></div>
        </div>
        
        {children}</body>
    </html>
  );
}
